project:
  type: website
  output-dir: docs

website:
  title: ""
  navbar:
    logo: "assets/reading.png"
    right:
      - index.qmd
      - about.qmd
      - icon: github
        href: https://github.com/
    menu:
      - text: Source Code
        url: https://github.com/jracker/blog
      - text: Report a bug
        url: https://github.com/jracker/blog/issues

format:
  html:
    css: styles.css
    theme: 
      light: [litera, custom.scss]
      # dark: [solar, custom.scss]
    highlight-style: gruvbox
    smooth-scroll: true
    
editor: visual

